<?php
/**
 * @file
 * Hello World demonstrates the use of SimpleTest for Drupal 7.
 */

/**
 * Implements hook_menu().
 */

function printtable_menu() {
  $items = array();

  $items['printtable'] = array(
    'title' => 'print table',
    'access callback' => TRUE,
    'page callback' => 'printtable_hello_page',
    'type' => MENU_NORMAL_ITEM,
    'menu' => 'navigation',
  );

  return $items;
}


function printtable_hello_page() {
 //$result;
 //$a;
 //$i; 


$a=$_GET['table'];
//echo $a;
//die();

for($i=1;$i<=15;$i++)
    {
   

    @$result .= $i."*".$a."=".$i*$a."<br>";

    }
      return ($result);
}

